import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const buttonCssStyle =
  "bordered rounded-full   px-3 py-1 bg-[#eef2ff] select-none hover:text-[#e0e7ff] hover:bg-purple-600 ";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} flex h-[100vh] flex-col bg-gray-300`}
      >
        <header className=" flex w-full justify-center bg-gray-200">
          <div className="flex w-[1080px] gap-10 p-4">
            <div>Logo</div>
            <div className="flex gap-10 text-purple-600 ">
              <div className={buttonCssStyle}>home</div>
              <div className={buttonCssStyle}>about</div>
              <div className={buttonCssStyle}>github</div>
              <div className={buttonCssStyle}>leaderboard</div>
            </div>
            <div className="grow"></div>
            <div
              className={
                "bordered rounded-full   bg-purple-600 px-3 py-1 text-[#eef2ff] hover:bg-[#eef2ff] hover:text-purple-600"
              }
            >
              login
            </div>
          </div>
        </header>
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
        <footer className="m-5">footer</footer>
      </body>
    </html>
  );
}
