import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const buttonCssStyle = "bordered rounded-full bg-[#eef2ff]  px-3 py-1 select-none hover:bg-[#e0e7ff] ";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} bg-gray-200 h-[100vh] flex flex-col`}>
        <header className=" flex w-full justify-center bg-gray-100">
          <div className="flex w-[1080px] gap-10 p-4">
            <div>Logo</div>
            <div className="flex gap-10">
              <div className={buttonCssStyle}>home</div>
              <div className={buttonCssStyle}>about</div>
              <div className={buttonCssStyle}>github</div>
              <div className={buttonCssStyle}>leaderboard</div>
            </div>
            <div className="grow"></div>
            <div className={buttonCssStyle + "bg-purple-600 text-[#eef2ff] hover:bg-[#eef2ff] hover:text-purple-600"}>login</div>
          </div>
        </header>
        <TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
